%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.9 (R2020b) and Database Toolbox Version 10.0 on 25-Nov-2021 14:50:05

%% Make connection to database
conn = database('Server97','sa','');

%Set query to execute on the database
query = ['SELECT StoricoAnalogiche.DataMisura, StoricoAnalogiche.Count,  StoricoAnalogiche.Cod7 , StoricoAnalogiche.diag' ...
    ' ' ...
    'FROM ( IOTSmartOSS_HistoricDB.dbo.StoricoAnalogiche ' ...
    'INNER JOIN IOTSmartOSS_HistoricDB.dbo.Tab7 ' ...
    'ON StoricoAnalogiche.Cod7 = Tab7.ID) ' ...
    'WHERE StoricoAnalogiche.Cod7 IN (SELECT Tab7.ID where StoricoAnalogiche.Cod7 = 173 or StoricoAnalogiche.Cod7= 180 or StoricoAnalogiche.Cod7= 187 or StoricoAnalogiche.Cod7=460 or StoricoAnalogiche.Cod7=424 or StoricoAnalogiche.Cod7=464 or StoricoAnalogiche.Cod7=465 or StoricoAnalogiche.Cod7= 186 or StoricoAnalogiche.Cod7= 185 or StoricoAnalogiche.Cod7= 184 or StoricoAnalogiche.Cod7 = 172) ' ...
    'and StoricoAnalogiche.Tag like (''%.1025.%'') and StoricoAnalogiche.DataMisura > ''2021-05-01 01:00:00.000'' ' ...
    'ORDER BY StoricoAnalogiche.DataMisura ASC'];

%% Execute query and fetch results
sqldata = fetch(conn,query);
%% Close connection to database
close(conn)

%% Clear variables
clear conn query